services:
  museum:
    build:
      context: ..
    ports:
      - 8081:8080
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ENTE_DB_HOST=postgres
      - ENTE_DB_PORT=5432
      - ENTE_DB_NAME=${POSTGRES_DB}
      - ENTE_DB_USER=${POSTGRES_USER}
      - ENTE_DB_PASSWORD=${POSTGRES_PASSWORD}
      - ENTE_DB_SSLMODE=disable
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - ENTE_API_ORIGIN=${ENTE_API_ORIGIN}
      - ENTE_ALBUMS_ORIGIN=${ENTE_ALBUMS_ORIGIN}
      - ENTE_S3_ACCESS_KEY_ID=ente_minio_admin
      - ENTE_S3_SECRET_ACCESS_KEY=${ENTE_S3_SECRET_ACCESS_KEY}
      - ENTE_S3_BUCKET_NAME=b2-eu-cen
      - ENTE_S3_ENDPOINT=http://minio:3200
      - ENTE_S3_REGION=${ENTE_S3_REGION}
    command: ["--config-file", "/etc/ente/museum.yaml"]
    volumes:
      - ./data:/data:ro
    networks:
      - default

  socat:
    image: alpine/socat
    network_mode: service:museum
    depends_on: [museum]
    command: "TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200"

  postgres:
    image: postgres:15-trixie
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      start_period: 30s
      start_interval: 1s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default
      - dokploy

  minio:
    image: minio/minio
    ports:
      - 3200:3200
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - minio-data:/data
    post_start:
      - command: |
          sh -c '
          #!/bin/sh
          while ! mc alias set h0 http://minio:3200 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} 2>/dev/null
          do
            echo "Waiting for minio..."
            sleep 0.5
          done
          cd /data
          mc mb -p b2-eu-cen
          mc mb -p wasabi-eu-central-2-v3
          mc mb -p scw-eu-fr-v3
          '
    networks:
      - default

  ente-web:
    build:
      context: ../../web
      args:
        - NEXT_PUBLIC_ENTE_ENDPOINT=${ENTE_API_ORIGIN}
        - NEXT_PUBLIC_ENTE_ALBUMS_ENDPOINT=${ENTE_ALBUMS_ORIGIN}
    ports:
      - 3003:3000
      - 3004:3001
      - 3005:3002
      - 3006:3003
      - 3007:3004
    environment:
      - NODE_ENV=production
      - ENTE_API_ORIGIN=${ENTE_API_ORIGIN}
      - ENTE_ALBUMS_ORIGIN=${ENTE_ALBUMS_ORIGIN}
      - NEXT_PUBLIC_ENTE_ENDPOINT=${ENTE_API_ORIGIN}
      - NEXT_PUBLIC_ENTE_ALBUMS_ENDPOINT=${ENTE_ALBUMS_ORIGIN}
    depends_on:
      - museum
    networks:
      - default
      - dokploy

volumes:
  postgres-data:
  minio-data:

networks:
  default:
  dokploy:
    external: true
    name: dokploy-network
